Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,4 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
 name: Node.js CI
 on:
   push:
@@ -6,17 +5,6 @@ on:
 jobs:
   build:
     runs-on: self-hosted
-    services:
-      # Add Redis service container
-      redis:
-        image: redis
-        ports:
-          - 6379:6379
-        options: >-
-          --health-cmd "redis-cli ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
     strategy:
       matrix:
         node-version: [22.x]
@@ -42,7 +30,6 @@ jobs:
         echo "PRO_DB_NAME=${{ secrets.PRO_DB_NAME }}" >> .env
         echo "TOKEN_DISCORD=${{ secrets.TOKEN_DISCORD }}" >> .env
         echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}" >> .env
-        # Set Redis host to localhost as the Redis service is running on the same machine
         echo "REDIS_HOST=localhost" >> .env
         echo "REDIS_PORT=6379" >> .env
         echo "RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}" >> .env
@@ -59,12 +46,16 @@ jobs:
         echo "AWS_CLOUDFRONT_DOMAIN=${{ secrets.AWS_CLOUDFRONT_DOMAIN }}" >> .env
         echo "AWS_CLOUDFRONT_PUBLIC_KEY_ID=${{ secrets.AWS_CLOUDFRONT_PUBLIC_KEY_ID }}" >> .env
         echo "AWS_CLOUDFRONT_PRIVATE_KEY=${{ secrets.AWS_CLOUDFRONT_PRIVATE_KEY }}" >> .env
-    - name: Install Redis CLI
+    - name: Check if Redis is running
       run: |
-        sudo apt-get update
-        sudo apt-get install -y redis-tools
-    - name: Verify Redis connection
-      run: |
-        redis-cli ping
+        # Check if Redis is running
+        if ! pgrep -x "redis-server" > /dev/null; then
+          echo "Redis server is not running. Starting Redis..."
+          sudo systemctl start redis || sudo service redis-server start || redis-server &
+        else
+          echo "Redis server is already running."
+        fi
+        # Test Redis connection
+        redis-cli ping || echo "Failed to connect to Redis. Please make sure Redis is installed and running."
     - name: Start application
       run: npm start
